spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ChessTournament
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: brahmsisme@gmail.com
    password: ladg wwkb fmkx atsr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080